POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "pog3",
  "url": "http://google.com"
}

###
DELETE http://localhost:3001/api/blogs/2
Content-Type: application/json

###
GET http://localhost:3001/api/blogs
Content-Type: application/json
###

PUT http://localhost:3001/api/blogs/3
Content-Type: application/json

{
  "url": "http://google.com",
  "likes": 2
}
 
