POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNvZjJlckBnbWFpbC5jb20iLCJpZCI6MiwiaWF0IjoxNjU4NjY5OTM3fQ.4ZuTGLHCBSYTFxh0ypGKu4F7anTGXg0kCicSnUk1RmU

{
  "title": "Great Adventure",
  "author": "Bill Gatsby",
  "url": "http://google.com",
  "likes": 5,
  "year": 1995
}

###
DELETE http://localhost:3001/api/blogs/6
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRkcXVpbjQyMCIsImlkIjoxLCJpYXQiOjE2NTg1NzMxMDF9.cdPUz8zs1NDT0RXhrWtYkT0a2wHYCrzM8yO6ni7zrTw


###
GET http://localhost:3001/api/blogs
Content-Type: application/json

###
GET http://localhost:3001/api/blogs?search=bill
Content-Type: application/json
###

PUT http://localhost:3001/api/blogs/11
Content-Type: application/json

{
  "url": "http://google.com",
  "likes": 11
}

###
GET http://localhost:3001/api/users
Content-Type: application/json
###

POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "sof2er@gmail.com",
  "name": "Sof"
}
###
PUT http://localhost:3001/api/users/ddquin
Content-Type: application/json

{
  "username": "ddquin420"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "sof2er@gmail.com",
  "password": "secret"
}

###
GET http://localhost:3001/api/authors
Content-Type: application/json
###

POST http://localhost:3001/api/readinglists
Content-Type: application/json

{
  "blogId": 2,
  "userId": 2
}

###
GET http://localhost:3001/api/users/2
Content-Type: application/json

 
