POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRkcXVpbjQyMCIsImlkIjoxLCJpYXQiOjE2NTg1NzMxMDF9.cdPUz8zs1NDT0RXhrWtYkT0a2wHYCrzM8yO6ni7zrTw

{
  "title": "Great adventure",
  "author": "Bill Gattsby",
  "url": "http://google.com",
  "likes": 2
}

###
DELETE http://localhost:3001/api/blogs/6
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRkcXVpbjQyMCIsImlkIjoxLCJpYXQiOjE2NTg1NzMxMDF9.cdPUz8zs1NDT0RXhrWtYkT0a2wHYCrzM8yO6ni7zrTw


###
GET http://localhost:3001/api/blogs
Content-Type: application/json

###
GET http://localhost:3001/api/blogs?search=bill
Content-Type: application/json
###

PUT http://localhost:3001/api/blogs/9
Content-Type: application/json

{
  "url": "http://google.com",
  "likes": 3
}

###
GET http://localhost:3001/api/users
Content-Type: application/json
###

POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "sof2er2@gmail.com",
  "name": "Sof2"
}
###
PUT http://localhost:3001/api/users/ddquin
Content-Type: application/json

{
  "username": "ddquin420"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "sof2er",
  "password": "secret"
}

 
